GET http://127.0.0.1:5000/

###

POST http://127.0.0.1:5000/soma
Content-Type: application/json

{
    "num1":20,
    "num2":50
}

###

GET http://127.0.0.1:5000/somados
Content-Type: application/json

###

GET http://127.0.0.1:5000//historico
Content-Type: application/json